### PR TITLE
Styling pass 1

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by smarnach** [comment]
@e-kolpakov Is the new version form this PR on some sandbox or QA instance?  This would be helpful for the styling changes.

The code changes look good to me, except for the one comment I had.

**Comment by e-kolpakov** [comment]
@smarnach no, it's not deployed anywhere yet. The thing is I have no control over QA instance except whatever is merged to master get's deployed to QA twice a day. And setting up our sandboxes is not going to help as they don't run Apros, and for now GP v2 only properly work in Apros. There's a ticket to make it run in LMS as well - I'll try to work on it if I have some time before/during/after QA session. So, unfortunately, there isn't any convenient way to view this - you've got to actually set it up in your local solutions devstack.

**Comment by smarnach** [comment]
@e-kolpakov Fine – I've managed to get it completely running locally by now (I included the GROUP_PROJECT_ prefix in section headings in my earlier attempts before noticing you discussed that issue on the ticket).

**Comment by e-kolpakov** [comment]
@smarnach yes, GP v2 definitely needs some documentation for authors.

**Comment by smarnach** [comment]
Styling looks mostly good on Chrome.  There seems to be a little less whitespace overall than in the mock up, but this might be due to the slightly different font sizes you mentioned.

One issue I noticed is that the left edge of multiline list items isn't aligned correctly – subsequent lines are less indented than the first line.
image

**Comment by smarnach** [comment]
:+1: Once the mentioned styling issue is resolved.

**Comment by smarnach** [comment]
One more difference I noticed now:  The mock-up has a blurred shadow instead of a grey border, which makes some difference to the overall appearance as a card stacked on top of the main content area.

**Pull request merged**
