### PR TITLE
MCKIN-27922: fix global gettext override

### PR DESCRIPTION
**Pull request by msaqib52**
This PR fixes global `gettext` override due to which `gettext` was unable to access translations catalog other than gpv2 hence no other translations were working.

### CODE REVIEW

**Comment by msaqib52** [comment]
@xitij2000 I think we started using namespaces for xblocks because [django was overriding catalog till django 1.8](https://github.com/django/django/blob/1.8.19/django/views/i18n.py#L96) and because we had multiple catalogs(apros, platform, xblocks) we could not use them simultaneously but starting [django 1.11 it has started appending catalogs](https://github.com/django/django/blob/1.11.29/django/views/i18n.py#L111) if there are multiple catalogs it will append them all and they all can be used simultaneously. Now the only purpose i see for these xblock namespaces is if we want different translations for same string with respect to its context if that is not the case then i think we should remove this namespacing to avoid issues like this one.

**Comment by xitij2000** [comment]
@msaqib52 Are you sure that will work? edx-platform doesn't use the dynamic catalogue, but a static one.

**Comment by msaqib52** [comment]
> @msaqib52 Are you sure that will work? edx-platform doesn't use the dynamic catalogue, but a static one.

@xitij2000 I haven't tried the implementation yet but looking at the [code here](https://github.com/django/django/blob/1.11.29/django/views/i18n.py#L111..#L117)  i think it should work as long as all the static django.js files are generated using Django>=1.11. But that is just a suggestion we can try the approach in any future PRs if it works for you.

**Review by xitij2000 — APPROVED** [review]

**Comment by xitij2000** [comment]
@msaqib52 Could you create a PR against the v0.10 branch as well if this needs to go before juniper.

**Comment by xitij2000** [comment]
Also please rebase and bump the version.

**Comment by msaqib52** [comment]
@xitij2000 rebased this PR and also created https://github.com/open-craft/xblock-group-project-v2/pull/159 against v0.10 branch

**Comment by msaqib52** [comment]
@xitij2000 Gentle reminder to merge this PR and https://github.com/open-craft/xblock-group-project-v2/pull/159

**Pull request merged**
