### PR TITLE
Added caching to requests that significantly slow down initial loading.

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by Kelketek** [comment]
fullscreen_8_3_15__10_07_am

@e-kolpakov  I'm getting weird effects from this PR. It's still pretty slow, and the above render is what I'm seeing.

I also get this error message when loading groupwork:

```
2015-08-03 11:09:22,062 ERROR 3408 [group_project_v2.api_error] api_error.py:58 - Error calling mark_as_complete: ApiError 'Resource already exists' (409)
Traceback (most recent call last):
  File "/edx/app/edxapp/xblocks/xblock-group-project-v2/group_project_v2/api_error.py", line 55, in call_api_method
    return func(*args, **kwargs)
  File "/edx/app/edxapp/xblocks/xblock-group-project-v2/group_project_v2/project_api.py", line 212, in mark_as_complete
    return self.send_request(POST, (COURSES_API, course_id, 'completions'), data=completion_data)
  File "/edx/app/edxapp/xblocks/xblock-group-project-v2/group_project_v2/project_api.py", line 58, in send_request
    response = method(url, data)
  File "/edx/app/edxapp/xblocks/xblock-group-project-v2/group_project_v2/json_requests.py", line 38, in make_request
    response = func(*args, **kwargs)
  File "/edx/app/edxapp/xblocks/xblock-group-project-v2/group_project_v2/json_requests.py", line 62, in POST
    return url_access.urlopen(url_request, json.dumps(data), TIMEOUT)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 409: CONFLICT
```

And I'm not sure why I would, because I'm not doing anything in particular other than loading the group work.

**Comment by e-kolpakov** [comment]
@Kelketek double PN - update apros to latest please :)

HTTPError - it's totally normal - certain stages are marked as complete on view, and if they were already it logs 409, but proceeds.

Slowliness -  it is still sluggish, but should be much less sluggish than earlier. For me it went from ~15 seconds to 3.5.

**Comment by Kelketek** [comment]
@e-kolpakov Just updated to the latest Apros.

When I try to view the Groupwork, I get:

```
Traceback:
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  88.                 response = middleware_method(request)
File "/edx/app/apros/mcka_apros/accounts/middleware/session_timeout.py" in process_request
  10.         if not request.user.is_authenticated():
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/utils/functional.py" in inner
  213.             self._setup()
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/utils/functional.py" in _setup
  298.         self._wrapped = self._setupfunc()
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py" in <lambda>
  18.         request.user = SimpleLazyObject(lambda: get_user(request))
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py" in get_user
  10.         request._cached_user = auth.get_user(request)
File "/edx/app/apros/venvs/mcka_apros/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py" in get_user
  144.         user = backend.get_user(user_id) or AnonymousUser()
File "/edx/app/apros/mcka_apros/accounts/json_backend.py" in get_user
  45.                 user = self._load_user(user_response)
File "/edx/app/apros/mcka_apros/accounts/json_backend.py" in _load_user
  21.         user.update_response_fields(user_response, auth_token)
File "/edx/app/apros/mcka_apros/accounts/models.py" in update_response_fields
  36.         self.is_staff = user_response.is_staff
```

**Comment by Kelketek** [comment]
:+1:

**Comment by e-kolpakov** [comment]
Closing in favor of #30

**Pull request closed without merging**
