### PR TITLE
Fixes from QA - batch 5

### PR DESCRIPTION
**Pull request by e-kolpakov**
* https://edx-wiki.atlassian.net/browse/MCKIN-3471 Proficiency score - When graded a group activity for gw v2, the proficiency score does not updated
* https://edx-wiki.atlassian.net/browse/MCKIN-3501 When group has been evaluated, members of that group doesn't received notification for posting grades
* https://edx-wiki.atlassian.net/browse/MCKIN-3502 Page is not loading for IE - 9,10
* https://edx-wiki.atlassian.net/browse/MCKIN-3473 UI - Change order of buttons on Project Navigator => Already fixed in https://github.com/open-craft/xblock-group-project-v2/commit/8ce0ce6d20dd0b82a09aa6463dfc4d6762bfd621 but with the wrong order

**Testing instructions:**
1. Score and grade notification - create a graded activity, set min rquired reviews to one (to simplify testing), add peer review stage + as many questions as you'd like. Create at least two groups (one student in each is enough) and generate review assignments via McKA admin. Log in as one student, go to course progress page (add `/progressv2` to course home page URL); mark all notifications as read (also make sure notifications are sent). Perform all the required reviews for the group that student is in (in  other browser or incognito window). *Expected result:* after last review, user receives notification "Grades available" immediately; proficiency score is updated on progress page when it is reloaded.
2. IE 9,10 - GP loads successfully (smoke test)
3. PN button order - correct order is: submissions, resources, private discussion, TA

### CODE REVIEW

**Comment by bradenmacdonald** [comment]
@e-kolpakov 

1. Code looks good.
2. FYI, I noticed this in my logs while setting up GPv2 in Studio, though it doesn't seem to cause any issues:

   ```
Traceback (most recent call last):
  File "/edx/xblocks/xblock-group-project-v2/group_project_v2/mixins.py", line 83, in user_id
    return int(self.real_user_id(self.anonymous_student_id))
  File "/edx/xblocks/xblock-group-project-v2/group_project_v2/mixins.py", line 110, in real_user_id
    self._known_real_user_ids[anonymous_student_id] = self.runtime.get_real_user(anonymous_student_id).id
TypeError: 'NoneType' object is not callable
```

3. Proficiency score: I can see the new grade on the progress v2 page, but the proficiency score is still '0' - do you know what I might be missing?
 
    screen shot 2015-11-06 at 6 04 06 pm

   (The LMS also says my grade is zero and that the group project block is not reporting any grades:)
   
    screen shot 2015-11-06 at 6 04 27 pm

4. Notifications: I did not see any notifications :(  Are there any other criteria on when the notifications will be shown?  (Note: when I first started testing, I did get a random "You are now #3 for Progress in the cohort!" notification, so I believe notifications are working in general on my devstack)
5. When I tried this at first, it didn't seem to work because I didn't realize that the `gp-v2-stage-peer-review` block requires a `gp-v2-group-selector` - it would be nice if there was a validation message for that.
6. Button order - looks good
7. Here is something that seemed weird to me: When I did the review step, it told both students that they were reviewing "Group 1", even though Student1 was actually reviewing Group 2. Is this a misunderstanding on my part, or is it showing the wrong group name to one of the students?
    screen shot 2015-11-06 at 6 14 49 pm
    screen shot 2015-11-06 at 6 12 07 pm
    screen shot 2015-11-06 at 6 12 57 pm

**Comment by bradenmacdonald** [comment]
Update: I tried again with a new group project block, and this time the proficiency did update. However, the only notification that I got was "You are now #3 for Proficiency in the cohort!". There was no notification about a grade being available. (The grade does appear on the ProgressV2 page though)

I also tested in IE9 and that part seems to be working.


So: The only thing that I have not been able to confirm yet is the "Grades Available" notification.

**Comment by e-kolpakov** [comment]
@bradenmacdonald 
1. Cool :)
2. That's because studio runtime does not provide `get_real_user`. In such case GP just falls back to using plain `anonymous_student_id`, but logs an exception so we have a log record.
3. Ok.
4. Weird, I'll check that again, but it works for me :)
5. Makes sense, but not sure if I can fit it in the current scope.
6. Great :)
7. By design. :) The idea is that groups are not labeled, so the numbers are just sequential. It causes a lot of confusion though, so I'll ask McK about changing that again. (QA also thought it's a bug).

**Comment by e-kolpakov** [comment]
@bradenmacdonald added validation for peer and group selectors (+tests). Unfortunately, I can't reproduce the issue with *not* sending grade notification - could you please check it out one more time? Anything that would help to reproduce that issue is very helpful as well :)

**Comment by bradenmacdonald** [comment]
@e-kolpakov I didn't see any errors or anything so I'm not sure why the grade notification didn't appear. Do you have a sample course you can share with me on JIRA? I might have set something up wrong.

**Comment by e-kolpakov** [comment]
@bradenmacdonald https://tasks.opencraft.com/browse/OC-649 contains three exported courses. You might want to give a shot with GP V2_NC - it's the latest one I have.

**Comment by bradenmacdonald** [comment]
@e-kolpakov I tried again with the course you recommended but still didn't see any grade notifications :-/

However, this time I noticed the error message that must be the cause:

```
Traceback (most recent call last):
  File "/edx/xblocks/xblock-group-project-v2/group_project_v2/utils.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/edx/xblocks/xblock-group-project-v2/group_project_v2/notifications.py", line 182, in fire_grades_posted_notification
    msg_type = notifications_service.get_notification_type(NotificationMessageTypes.GRADES_POSTED)
  File "<string>", line 2, in get_notification_type
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/contracts/main.py", line 266, in contracts_checker
    result = function_(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/src/edx-notifications/edx_notifications/lib/publisher.py", line 63, in get_notification_type
    return notification_store().get_notification_type(type_name)
  File "/edx/app/edxapp/venvs/edxapp/src/edx-notifications/edx_notifications/stores/sql/store_provider.py", line 108, in get_notification_type
    raise ItemNotFoundError()
ItemNotFoundError
```

I'm not very familiar with notifications - is this error something that I have not done properly (like a migration), or is this an issue with your code? 

I'm starting my holidays now so won't be able to respond. But I'm :+1: on everything here *if* either (A) that error is my fault because of a misconfiguration, or (B) you fix that error :)

Screenshot after a student's work is reviewed by another student (I changed the block to only require 1 review):
screen shot 2015-11-09 at 9 24 01 pm

**Comment by e-kolpakov** [comment]
@bradenmacdonald gp switched to using their own notification types, which are stored in the DB and registered somewhere in edx-notifications repo. So if you haven't updated to the latest edx-notfications version - the error makes total sense. To prevent that in the future I'll add a dependency on edx-notification to GP.

**Pull request merged**
