### PR TITLE
MCKIN-27921 symlink and missing translations

### PR DESCRIPTION
**Pull request by mudassir-hafeez**
Stage templates were not translating from an XBlock-specific GNU gettext translator as I18n service expects translations directory at the same level where xblock module is located. So created a symlink for translations directory in the stage directory to provide a dedicated translation catalog. And also added a few new translations.

### CODE REVIEW

**Comment by mudassir-hafeez** [comment]
@xitij2000 can you please review?
Here is the PR #161 against master.

**Comment by mudassir-hafeez** [comment]
@xitij2000 just a gentle reminder 🙂 as this PR needs to be merged.

**Comment by viadanna** [comment]
@mudassir-hafeez I'm reviewing this, can you resolve conflicts and rebase?

**Comment by mudassir-hafeez** [comment]
@viadanna conflicts resolved. Thanks for reviewing.

**Review by viadanna — APPROVED** [review]
Good to go 👍

- [x] I tested this on my local devstack.
- [x] I read through the code.

**Pull request merged**
