### PR TITLE
MCKIN-29786 N/A string Marked for translations

### PR DESCRIPTION
**Pull request by musmanmalik**
N/A string Marked for translations

### CODE REVIEW

**Comment by musmanmalik** [comment]
@xitij2000 Please review.

**Review by xitij2000 — APPROVED** [review]
:+1:
- [x] I tested this: tested on juniper devstack. 
- [x] I read through the code

**Comment by xitij2000** [comment]
@musmanmalik Can you update base.txt to limit edx-opaque-keys to '>=0.4.0,<2.2.0'
Currently it seems to be installing 2.2 which is breaking tests.

**Comment by musmanmalik** [comment]
@xitij2000 Please merge and create tag. Thanks

**Comment by musmanmalik** [comment]
@xitij2000 Please create release tag. Sorry for inconvenience.

**Pull request merged**
