### PR TITLE
MCKIN-27923 portuguese was not working

### PR DESCRIPTION
**Pull request by musmanmalik**
portuguese was not working. its fixed now also a french string that was not getting translated fixed.
https://edx-wiki.atlassian.net/browse/MCKIN-27923

### CODE REVIEW

**Comment by musmanmalik** [comment]
@xitij2000 Please review this PR. This[master](https://github.com/open-craft/xblock-group-project-v2/pull/157).

**Review by xitij2000 — APPROVED** [review]
:+1:
- [x] I tested this:  tested on solutions devstack
- [x] I read through the code

**Comment by musmanmalik** [comment]
@xitij2000 It seems release not created correctly from v0.10 after merging this PR. Could you please check?

**Comment by xitij2000** [comment]
@musmanmalik I've fixed this.

**Pull request merged**
