### PR TITLE
Correct Project Team block's group membership check

### PR DESCRIPTION
**Pull request by Kelketek**

### CODE REVIEW

**Comment by Kelketek** [comment]
@e-kolpakov I noticed that this XBlock doesn't appear to have any tests-- any test that checked to see if it ran at all should have been able to catch the problem. I'm not entirely sure how one could effectively mock it out and verify it works. Do you have any idea if there's a good way to do this?

**Comment by e-kolpakov** [comment]
@Kelketek there are no integration tests for individual stage components; this block is really simple though, and it can be added to any stage, so if you use the approach similar to stage integration tests use you should be able to do that.

To be more precise, stage integration tests dynamically create workbench scenario XML. You would use the same approach, but instead of using different stage XML setups you can build stage + component XML.

**Comment by Kelketek** [comment]
@e-kolpakov This should be ready for your review now.

**Comment by Kelketek** [comment]
@e-kolpakov :+1:

**Comment by e-kolpakov** [comment]
@Kelketek this is the wrong PR I believe :)

**Comment by Kelketek** [comment]
@e-kolpakov You're correct. This is the one I need review on. I'll find the one I needed to put that +1 on and put it there.

**Comment by e-kolpakov** [comment]
@Kelketek :+1:

**Pull request merged**
