### PR TITLE
Javascript tests infrastructure, travis integration and some simple tests

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by smarnach** [comment]
Nice!  It doesn't test a whole lot so far, but it's good to have the infrastructure in place.  I guess we need to think about approaches to unit-test JavaScript in XBlocks in general.

The install section of `.travis.yml` is a bit of a mess – it contains a hard-coded hash and installs some of the dependencies multiple times at different versions.  We should clean this up at some point, because it is going to bite us, but right now is not the best time to do this. :)

:+1:

**Comment by e-kolpakov** [comment]
@smarnach hard-coded hash is there until a patch is merged to upstream xblock-sdk to support activate_block_id. Other than that, it might make sense to clean it up, but so far it runs `pip install -r` on different files, so it might be not possible to simplify it.

**Comment by smarnach** [comment]
@e-kolpakov Why don't we put the hash directly in requirements.txt then?

Generally, all that should be necessary to set up the test environment should be `pip install -r test-requirements.txt`.  It shouldn't be necessary to explicitly install the requirements of the requirements, unless there are version conflicts in the requirement graph and you have to enforce the installation order to end up with the right version of some transitive dependency.  I've found this to be brittle in the past, though, that's why I mentioned cleaning it up.  I also found that trying to clean up something like this often ends up being quite a deep rabbit hole.

**Comment by e-kolpakov** [comment]
@smarnach I believe there are some conflicts, because I basically used the same travis.yaml we had in problem-builder + if I recall correctly I've tried doing just `requirements.txt` and `test-requirements.txt` and moving sdk and stuff into test-requirements - it didn't work well. I'll try again (maybe somethig have changed since than), but can't promise anything :)

**Comment by smarnach** [comment]
@e-kolpakov I also believe there are conflicts, and these conflicts should be cleaned up at some point.  It's great if you try to do that, but it's out of scope for this PR or any current task.  Feel free to merge this PR as it is.

We could also think about reducing conflicts by using version tags or branch names instead of hashes for all XBlock-related repositories in the long run.  The current approach has proven rather brittle and does not scale any further.

**Pull request merged**
