### PR TITLE
Studio fixes

### PR DESCRIPTION
**Pull request by e-kolpakov**
* Individual `display_name` fields for all stages - need to provide unique default names
* Fixed incorrect studio label for "Text" stage

### CODE REVIEW

**Comment by smarnach** [comment]
@e-kolpakov Please take a look at the test failures – they are mostly the same as in the other PR, so the errors seem to exist in master already.  There is one pep8 issue introduced by this commit (only one blank line before some class definition).

:+1: After fixing the pep8 issue and deciding what to do with the test failures.

**Comment by e-kolpakov** [comment]
@smarnach there's a dedicated branch to fix tests - they should be ready by the end of the sprint. Basically, existing tests are integration ones, written before real children conversion - so they fail mostly due to changed XBlock categories (and XML node names). Please ignore failing tests for now, until I send a PR saying "Fixing integration tests" :)

**Comment by smarnach** [comment]
@e-kolpakov Sounds good – so it's just the missing blank line to fix for this PR.

**Comment by e-kolpakov** [comment]
@smarnach fixed, but I'm not going to merge it today - Xavier have demo today, so he asked to delay any merges to avoid "last minute critical bug" syndrome :)

**Pull request merged**
