### PR TITLE
More fixes from QA

### PR DESCRIPTION
**Pull request by e-kolpakov**
* More PN view title updates
* Wider PN (35% width)
* Submissions view styling: borders around input controls, updated placeholder text

### CODE REVIEW

**Comment by smarnach** [comment]
@e-kolpakov Code looks good.  I couldn't test this so far since I'm getting [weird tracebacks](https://gist.github.com/smarnach/f768c66fd24da3e7bcd5) when using the version from this branch, which don't look like they could be caused by the changes in this PR.  Any ideas?

**Comment by e-kolpakov** [comment]
@smarnach it is likely caused by Private Discussion View - this branch knows nothing about it. I've just merged private discussion branch, so as soon as I rebase this on top of master the issue should vanish.

**Comment by smarnach** [comment]
@e-kolpakov Right, I added a private discussion view to that course.  I'll wait for the revase then.

**Comment by e-kolpakov** [comment]
@smarnach rebased

**Comment by smarnach** [comment]
:+1:

**Pull request merged**
