### PR TITLE
Discussions support

### PR DESCRIPTION
**Pull request by e-kolpakov**

### CODE REVIEW

**Comment by smarnach** [comment]
The contents of the modal spills over the edge after clicking "New post" on Chrome:

image

**Comment by smarnach** [comment]
What's the point of the "Show Discussion" button inside the modal?  If I click the button to pop up the modal, chances are I want to see the discussion.  I think it's a bit confusing that the discussion is hidden by default, and you can only see it after expanding it.

**Comment by smarnach** [comment]
@e-kolpakov This looks quite good overall!  I've got a few comments and questions, and I'll take another look tomorrow.

**Comment by e-kolpakov** [comment]
@smarnach content spillover - weird, I've fixed that once :) I'll take another look on it.

"Show Discussion" - this is how Discussion XBlock works - it starts collapsed as normally it is inlined into a lesson content. For the scope of current release it was decided we'll go with whatever discussion offers now - but we're likely to modify it in future.

**Comment by smarnach** [comment]
:+1: The new version looks great.  If there is an easy way to have the discussion expanded by default (without touching the Discussion XBlock code base), I think we should do that.  Otherwise, It's fine to defer that until later.

**Pull request merged**
